--- #YAML:1.0
name:                HTML2XHTML
version:             0.04b
abstract:            ~
license:             ~
author:              ~
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Cwd:                           3.05
    File::Flock:                   104.111901
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
