# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML2XHTML
version:      0.03.02
version_from: lib/HTML2XHTML/HTML2XHTML.pm
installdirs:  site
requires:
    Cwd:                           

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
